import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
padding = {x = 3, y = 3}
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = {family = "Maple Mono SC NF", style="Light"}
bold = {family = "Maple Mono SC NF", style="Regular"}
italic = {family = "Maple Mono SC NF", style="LightItalic"}
bold_italic = {family = "Maple Mono SC NF", style="BoldItalic"}
size = 14
