# .bashrc
set -o vi

# XDG Specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# environment variables
export EDITOR="/usr/bin/nvim"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# aliases
alias lvim="NVIM_APPNAME=lazyvim nvim"
alias lgit="lazygit"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# PATH variable
if ! [[ "$PATH" =~ "$XDG_DATA_HOME/pyenv/bin:" ]]; then
	PATH="$XDG_DATA_HOME/pyenv/bin:$PATH"
fi
if ! [[ "$PATH" =~ "$HOME/bin:" ]]; then
	PATH="$HOME/bin:$PATH"
fi
if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi
unset rc
