#!/bin/zsh

# XDG base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# TODO: change

# XDG Base Directory
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/config.toml"

# jupyter notebook
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/.config/jupyter"
export JUPYTER_DATA_DIR="$XDG_DATA_HOME/jupyter"

# applications
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"

# locale
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# pyenv
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# pipx
export PIPX_HOME="$XDG_DATA_HOME/pipx"
export PIPX_MAN_DIR="$XDG_DATA_HOME/man"
export PIPX_BIN_DIR="$HOME/.local/bin"
export PIPX_DEFAULT_PYTHON="$XDG_DATA_HOME/pyenv/versions/3.11.7/bin/python"

# PATH
export PATH="/usr/local/sbin:$PATH"
export PATH

# FPATH
fpath+="$XDG_CONFIG_HOME/zsh/.zfunc"                      # autocompletion poetry and docker
fpath+="$XDG_CONFIG_HOME/zsh/plugins/zsh-completions/src" # additional completion definitions
export FPATH
