start-at-login = true
automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-shift-semicolon = 'mode service'
alt-shift-slash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'

alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# Assigning workspaces to applications

[[on-window-detected]]
if.app-id = 'org.libreoffice.script'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = "com.colliderli.iina"
run = ["layout floating", 'move-node-to-workspace 1']

# Browser applications

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 2'

# Terminal applications

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout floating", "layout tiling", 'move-node-to-workspace 3']

# Calendar

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 4'

# Slack

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 5'

# Mail

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 6'

# AI applications

[[on-window-detected]]
if.app-id = 'ai.elementlabs.lmstudio'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'ai.elementlabs.lmstudio'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace 7'

# Messaging applications

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 8'

# Picture-in-Picture: floating by default

[[on-window-detected]]
if.during-aerospace-startup = false
if.app-id = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']
